// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jswejhxrdnvwxonyaopz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impzd2VqaHhyZG52d3hvbnlhb3B6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDUwNTAsImV4cCI6MjA2NzEyMTA1MH0.pK9rMFafMN-M91E3pdG8A8c73f9Gs8_BRgkZVLDblC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});